### ISSUE TITLE
acmetools only binds on localhost when acting as proxy

### ISSUE THREAD

**Issue by mikabak** [hlandau/acme#208]
Perhaps a design decision but also very limiting factor for my use case.
I would like to run acmetool on a backend server behind nginx proxy servers fronting the internet. The acmetool is consequently NOT running on the same hardware as the frontends.

I did not find a way to make acmetool bind on anything else but localhost.  Is there?

I run the version available in Ubuntu PPA (0.0.58-1trusty1).

TIA,
Mikael

**Comment by hlandau** [comment]
You can do this by explicitly specifying a bind address for the `http-ports` parameter.

The `http-ports` configuration parameter supports the following syntaxes:

```
request:
  challenge:
    http-ports:
      - 123            # defaults to localhost only
      - 0.0.0.0:123
      - [::]:123
```

You can put this as a default in `conf/target`.

**Comment by mikabak** [comment]
Thanks alot! This was what I was looking for.

**Comment by mnalis** [comment]
I've also needed to change this, due to using `iptables -t nat -A PREROUTING -p tcp --dport 80 -d public_ip -j REDIRECT --to-port 4402` (and `iptables -t nat -A OUTPUT -p tcp --dport 80 -d public_ip -j REDIRECT --to-port 4402` for acmetool local test to work first), which will use `public_ip:4402` instead of `127.0.0.1:4402`

However with example config above I've kept getting `[ERROR] acme.storage: error loading default target file: yaml: line 9: did not find expected node content`. Took me some time to figure YAML stuff needs to be quoted, as example above did not work for me in acmetool 0.0.58-1~bpo8+1 from Debian jessie-backports...

So it should look like this:

```
request:
  provider: https://acme-v01.api.letsencrypt.org/directory
  key:
    type: rsa
  challenge:
    http-ports:
      - 4402            # this defaults to localhost only
      - "0.0.0.0:4402"
      - "[::]:4402"
```

and then it works just fine!
