### ISSUE TITLE
Legacy webroot-paths setting not working

### ISSUE THREAD

**Issue by kkofler** [hlandau/acme#210]
My targets under `/var/lib/acme/desired/*` all have one or more `webroot-paths` configured, e.g.:

```
names:
- www.calcforge.org
- calcforge.org
webroot-paths:
- /home/calcforge/www.calcforge.org/.well-known/acme-challenge
```

But `acmetool 0.0.58` no longer honors these. (I am not sure what version it last worked with. My last successful renewals were on 2016-08-31, in any case.) Instead, my renewals are failing because it tries to use the default `/var/run/acme/acme-challenge/` path.

**Comment by hlandau** [comment]
Can you try changing to:

```yaml
satisfy:
  names:
    - www.calcforge.org
    - calcforge.org
request:
  challenge:
    webroot-paths:
      - /home/calcforge/www.calcforge.org/.well-known/acme-challenge
```

Let me know if this works. This is the preferred syntax now, but the old syntax *should* still be supported, so this is surely a bug. But that should get things working for now at least.
