### ISSUE TITLE
environment not always set in hooks

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#225]
I've got an environment requested in a desired:
```
satisfy:
  names:
   ...
request:
  env:
    ACMETOOL_IS_DNS: 1
```
but if I add an `export >> /tmp/dump` at the start of the dns.hook it is not set:
```
root@acme:/var/lib/acme/desired# fgrep ACME /tmp/dump
declare -x ACME_STATE_DIR="/var/lib/acme"
declare -x ACME_STATE_DIR="/var/lib/acme"
declare -x ACME_STATE_DIR="/var/lib/acme"
declare -x ACME_STATE_DIR="/var/lib/acme"
declare -x ACME_STATE_DIR="/var/lib/acme"
declare -x ACME_STATE_DIR="/var/lib/acme"
```
