### ISSUE TITLE
provider in desired file sometimes not acknowledged

### ISSUE THREAD

**Issue by Mrten** [hlandau/acme#228]
There's a problem if you try to overrule the provider in a specific `desired` file.
I got this in `/var/lib/acme/conf/target`:
```
request:
  # default is staging, voorlopig
  provider: https://acme-staging.api.letsencrypt.org/directory
  key:
    type: rsa
    rsa-size: 2048
```
and i got this in a `/var/lib/acme/desired/xxx` file:
```
satisfy:
  names:
    - demo.ii.nl

request:
  provider: https://acme-v01.api.letsencrypt.org/directory
  challenge:
    webroot-paths:
      - /mnt/gluster/acme/demo.ii.nl
```
Also, much more files in `desired/` besides this one. 

Now, if I start over clean, with an empty `live/` and `certs/` and `keys/` directory, acmetool generates **staging** certificates, even for the domain in the `xxx` desired file. But if I then throw away that generated staging cert for `demo.ii.nl` and run acmetool again, so that it only has to request that one certificate, everything works fine and a-OK. 

Another hint is that It has something to go with the order certificates are requested in: I've got more provider overrides like that and not all of them got staging certs on the first run.
