### ISSUE TITLE
localhost:402 binding prevents usage in high-availability setups

### ISSUE THREAD

**Issue by jpotter** [hlandau/acme#236]
Hi,

I manage a setup that has two frontend nodes running varnish, for high availability. I'm able to get acmetool running fine when I test and configure varnish to pass requests through to 127.0.0.1:402.

However, for a two-node setup, I need to be able to have the second node route the request through to the first node (which I'm fine with -- don't need acmetool itself to be highly available.)

Is there a way to configure acmetool to listen on * instead of localhost?

Thanks,
Jeff

tcp        0      0 127.0.0.1:4402          0.0.0.0:*               LISTEN      23792/acmetool      
tcp        0      0 127.0.0.1:402           0.0.0.0:*               LISTEN      23792/acmetool      
tcp6       0      0 ::1:4402                :::*                    LISTEN      23792/acmetool      
tcp6       0      0 ::1:402                 :::*                    LISTEN      23792/acmetool

**Comment by gregorg** [comment]
You can specify ports in config file: https://github.com/hlandau/acme/blob/83d2466ceb01a76d281ff8983465db191fbfa1e2/_doc/SCHEMA.md

Example:

```
# cat /var/lib/acme/conf/target 
request:
  provider: https://acme-v01.api.letsencrypt.org/directory
  key:
    type: rsa
    rsa-size: 4096
  challenge:
    http-ports:
      - 0.0.0.0:402
```
