### ISSUE TITLE
Allow hostname variable in names specification

### ISSUE THREAD

**Issue by hlandau** [hlandau/acme#90]
It would be nice if a targetfile could be configured to always request the machine's current FQDN.
Something like
```yaml
satisfy:
  names:
    - example.com
    - $HOSTNAME
```
