### ISSUE TITLE
Multiple webroots and auto renew

### ISSUE THREAD

**Issue by tomwaldnz** [hlandau/acme#92]
I run half a dozen domains on my AWS Linux server. Each has its own webroot. I have a few questions around ACME.

1) Can acme create and automatically renew certificates for all of the domains?
2) Do I run quickstart for my first domain, request a certificate, then run quickstart again and request the next domain, etc?
3) Will auto renew still work given I have multiple webroots? ie will it remember all the certificates issued and renew them all?
4) I noticed a reference to creating a new crob job automatically. After I issued my first certificate I ran "crontab -e" and there were no new entries. Any ideas? I ran as root but didn't put "sudo" in front of the request to generate a certificate.

Thanks :-)

Tim

**Comment by hlandau** [comment]
1. Yes.
2. You only need to run quickstart once, not per domain.
3. Yes.
4. A cron entry is installed in /etc/cron.d.

In order to configure multiple webroots, you can either
a. put the webroot for a given target in the targetfile:
```yaml
request:
  challenge:
    webroot-paths:
      - /path/to/.well-known/acme-challenge
```
or
b. put all of the webroots in `conf/target`:
```yaml
request:
  challenge:
    webroot-paths:
      - /path/to/.well-known/acme-challenge
      - /path/to/some/other/.well-known/acme-challenge
```

However, you should seriously consider standardising on one webroot path and symlinking the others, or aliasing all to the same path in your vhost configs.
